modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/MightyDanp/TechAscension/issues"
license="AGPL-3.0 license"

[[mods]]
    modId="techascension"
    logoFile="techascension.png"
    version="0.0.0.1"
    displayName="Tech Ascension"
    displayURL=""
    authors="MightyDanp"
    description='''A simple but powerful coremod.'''

[[dependencies.techascension]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.techascension]]
   modId="techcore"
   type="required"
   ordering="BEFORE"
   side="BOTH"
   versionRange="[0.0.0.1,)"

[[mixins]]
   config="techascension.mixins.json"

[[accessTransformers]]
   file="META-INF/accesstransformer.cfg"